import axios from "axios";
import Head from "next/head";
import { Container, Row, Col } from "react-bootstrap";
import { HeaderBreadcrumb } from "../../components/structure/Breadcrumb/Breadcrumb";
import { Filter } from "../../components/contexts/Product/Filter";
import { OfferListing } from "../../components/contexts/Product/OfferListing";
import { SideAd } from "../../components/structure/SideAd";
import { HeaderNavbar } from "../../components/structure/Navbar";
import { Footer } from "../../components/structure/Footer";
import { API_URL, PER_PAGE } from "../../config";

const getProductPath = async () => {
  let offset = 0;
  let paths = [];

  try {
    while (paths.length < 15000) {
      const { data: products } = await axios.get(
        `${API_URL}/product?offset=${offset}&limit=${PER_PAGE}`
      );

      const ids = products.map((product) => ({
        params: {
          id: product.id,
        },
      }));

      paths = [...paths, ...ids];

      offset = offset + PER_PAGE;
    }
  } catch (error) {
    console.log(error);
  }

  return paths;
};

export const getStaticProps = async ({ params: { id } }) => {
  const { data } = await axios.get(`${API_URL}/product/${id}`);

  return {
    props: {
      product: data,
    },
  };
};

export const getStaticPaths = async () => {
  const paths = await getProductPath();

  return { paths, fallback: false };
};

const ProductPage = ({ product: { offers } }) => {
  return (
    <>
      <Head>
        <title>POC CliqueFarma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNavbar />
      <Container>
        <Row>
          <Col md={8}>
            <HeaderBreadcrumb />
            <Filter />
            <OfferListing offers={offers} />
          </Col>
          <Col md={4} className="d-none d-sm-block">
            <SideAd />
          </Col>
        </Row>
      </Container>
      <Footer />
    </>
  );
};

export default ProductPage;
