import Head from "next/head";
import { Container, Row, Col } from "react-bootstrap";
import { HeaderBreadcrumb } from "../components/Breadcrumb/Breadcrumb";
import { HeaderNavbar } from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNavbar />
      <Container>
        <Row>
          <Col>
            <HeaderBreadcrumb />
          </Col>
        </Row>
      </Container>
    </>
  );
}
