import Head from "next/head";
import { Container, Row, Col } from "react-bootstrap";
import { HeaderBreadcrumb } from "../components/structure/Breadcrumb/Breadcrumb";
import { Filter } from "../components/contexts/Product/Filter";
import { Listing } from "../components/contexts/Product/ProductListing";
import { SideAd } from "../components/structure/SideAd";
import { HeaderNavbar } from "../components/structure/Navbar";
import { Footer } from "../components/structure/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>POC CliqueFarma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNavbar />
      <Container>
        <Row>
          <Col md={8}>
            <HeaderBreadcrumb />
            <Filter />
            <Listing />
          </Col>
          <Col md={4} className="d-none d-sm-block">
            <SideAd />
          </Col>
        </Row>
      </Container>
      <Footer />
    </>
  );
}
